name: Build Test

on:
  push:
    # Don't run for tags
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  build-webos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install webOS NDK
        id: webos-ndk
        uses: webosbrew/setup-webos-ndk-action@main
        with:
          version: "webos-c592d84"

      - name: Install webOS CLI & Compatibility checker
        run: sudo npm install -g @webosbrew/compat-checker

      - run: npm ci

      - name: Build native
        env:
          CMAKE_TOOLCHAIN_FILE: ${{steps.webos-ndk.outputs.cmake-toolchain}}
        run: npm run build-service

      - name: Build frontend
        run: npm run build

      - name: Package
        run: npm run package

      - name: Compatibility Check
        run: "webosbrew-ipk-compat-checker --markdown --github-emoji --quiet *.ipk >> $GITHUB_STEP_SUMMARY"

      - name: Add Commit Hash Suffix
        shell: bash
        run: "for file in *.ipk ; do mv $file ${file//_all/-${GITHUB_SHA:0:8}_all} ; done"

      - uses: actions/upload-artifact@v3
        with:
          name: webos-snapshot
          path: "*.ipk"
